import { Open_Sans, Inter } from '@next/font/google'
import "./globals.css";
import '@fortawesome/fontawesome-free/css/all.min.css'; // Import Font Awesome CSS
import ThemeContextProvider from '@/app/context/themeContext';

const openSans = Open_Sans({ weight: ['400', '600'], subsets: ['latin'] })
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.className} ${inter.className}`}>
        <ThemeContextProvider>
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}